creation_rules:

  - path_regex: secrets/us-west-2-platform-engineering-prd
    encrypted_regex: "^(data|stringData)$"
    shamir_threshold: 1
    key_groups:
      - kms:
          - arn: arn:aws:kms:us-west-2:<redacted>:key/1913ee1f-6c69-4e91-abe9-8bab6b89ab88
            role: arn:aws:iam::<redacted>:role/flux-secrets-us-west-2

  - path_regex: secrets/us-west-2-platform-engineering-sbx
    encrypted_regex: "^(data|stringData)$"
    shamir_threshold: 1
    key_groups:
      - kms:
          - arn: arn:aws:kms:us-west-2:<redacted>:key/fedbdab9-12ed-4ad7-a71d-15c5ba4cb24e
            role: arn:aws:iam::<redacted>:role/flux-secrets-us-west-2
