creation_rules:

  - path_regex: secrets/us-west-2-platform-engineering-prd
    encrypted_regex: "^(data|stringData)$"
    shamir_threshold: 1
    key_groups:
      - age:
          - age1jt42rcckms34skz77t56wvtqxy56n9s0flttavg5qm240aghqg5svglwz9

  - path_regex: secrets/us-west-2-platform-engineering-sbx
    encrypted_regex: "^(data|stringData)$"
    shamir_threshold: 1
    key_groups:
      - age:
          - age1jt42rcckms34skz77t56wvtqxy56n9s0flttavg5qm240aghqg5svglwz9
