apiVersion: v1
kind: Secret
metadata:
    name: slack-token
    namespace: flux-system
data:
    token: ENC[AES256_GCM,data:vSOiv1Z0m1d4DwwvexWaOY8hRTaB0EV6Zw==,iv:4Jreltb0NK+VV1ePuyDEiYxBzlGlVQaErSo1LZohNcA=,tag:SqZySN21SdlOT0oONmMLOA==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jt42rcckms34skz77t56wvtqxy56n9s0flttavg5qm240aghqg5svglwz9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ1ZzSVE0WGs3WXI3T3pI
            NXpmODMwcWxMVHVBdTdSMW1zcDVkbjEvZmtVCjNIZlFoaUtpdFduMFJkTlFpcENS
            TnVuSk1aWnNBUTVmaWlVTDV0Njd2SzAKLS0tICtvUlNPdHFOcFZlWXp5S3JqK1NZ
            Nk8rRExBMVM2cU9PbkhtVUgwdWhEdTQKztuaZK5Iy6HXdFbXqu2qPDfNNtjkvo0N
            6HnNmUdKpuks57dJg56BpFteid2AkND2u4ga34zJuXJIDkF0iyH1PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T15:03:10Z"
    mac: ENC[AES256_GCM,data:cJywOskVM2Hobd504xj+AdIUJlsvHiFvuQX+xnmHxdliQddnLJkr76SxnPDaCo3uaLjohhpXnyelzLKFHUulNnPuQTZtz28YITGDTplfieaYYiBwCYldvUkZ04TQk/2FR/DfwZxf8sDdKjTcATU6Ywn7BbAgfVo4AuI4s1FPvKM=,iv:0iap2EHlbUb3JNSqkW1vyT+oNip/eYqCVNljecknmO0=,tag:vZoHu9QuBmSOhceWbnPjcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
