apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-redis-credentials
    namespace: oidc
data:
    redis-password: ENC[AES256_GCM,data:VcfTK0dJl6CGZNIuGoclG80YY8Qdu9IN,iv:AytNi8zZFeE8nYAs9nVA1iIN+8f/0gWxwGw+5W6ZSU8=,tag:cAC5HU68pZm5JXVpXKzf4Q==,type:str]
    redis-sentinel-password: ENC[AES256_GCM,data:yrxROrjcDdzU/ieOu61RwvNDZG1syexM,iv:9NvWbmwHVqXnivXgIfMyUkX1p2YUnebXLZsiX7k+1jg=,tag:vDDPanmWSZFFIJF7l19ptA==,type:str]
sops:
    shamir_threshold: 1
    kms:
    -   arn: arn:aws:kms:us-west-2:<REDACTED>:key/1913ee1f-6c69-4e91-abe9-8bab6b89ab88
        role: arn:aws:iam::<REDACTED>:role/flux-secrets-us-west-2
        created_at: '2022-01-05T11:08:05Z'
        enc: AQICAHjJQc8/3tTBOHU60YtvzJE+UdkYwT7Z4s5yhjI9sZjnOAGTAJJRl1e/1LnzBLRgKk5eAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFzun/Sbr9RebDeyLAgEQgDskfTtLPMxxlMUN9nhVyZDkQmJ925awR9VpsWhCtnLiqslmbrPeQzSLbums8hkKOmBB7KRXZry/9jzYXA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2022-01-05T11:08:07Z'
    mac: ENC[AES256_GCM,data:Sw/hXIyd1BzdanYOhWJzioKxr6jsa7y/YXlXwD7geRMcavIxuPNV/mBJLdKslwl4fazRPKRAj2kwxa5cinyscce0+a0D1dPonslFf5WQXA46Cv/vwhBLHx/Dz4jjn5KNAdVdGIUmnA9BRGXN2DPiHnk/QIhpyRlcIjjS2SeLjcQ=,iv:Zm2LzrDRLkH4r2X2MS8x25Lh4yGWNlZWhHi4J/LRkww=,tag:sr/g5eR4t7ltuIMn60Gmyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
